import { StyleSheet, Platform, StatusBar } from "react-native";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F6FA",
  },
  header: {
    backgroundColor: "#FF4B8B",
    paddingTop:
      Platform.OS === "android" ? (StatusBar.currentHeight ?? 24) + 12 : 52,
    paddingBottom: 20,
    paddingHorizontal: 20,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerBrand: {
    fontSize: 22,
    fontWeight: "800",
    color: "#fff",
    letterSpacing: 1,
  },
  headerSub: {
    fontSize: 12,
    color: "rgba(255,255,255,0.8)",
    marginTop: 2,
  },
  settingsBtn: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: "rgba(255,255,255,0.2)",
    justifyContent: "center",
    alignItems: "center",
  },
  settingsIcon: {
    fontSize: 18,
  },
  scroll: {
    flex: 1,
  },
  scrollContent: {
    padding: 20,
  },
  greeting: {
    fontSize: 22,
    fontWeight: "700",
    color: "#1a1a1a",
    marginTop: 8,
  },
  greetingSub: {
    fontSize: 14,
    color: "#888",
    marginTop: 4,
    marginBottom: 20,
  },
  cardsRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 14,
  },
  card: {
    flex: 1,
    borderRadius: 20,
    padding: 18,
    minHeight: 160,
    justifyContent: "space-between",
  },
  cardPink: {
    backgroundColor: "#FF4B8B",
  },
  cardPurple: {
    backgroundColor: "#0F6E56",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  cardLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "rgba(255,255,255,0.8)",
    letterSpacing: 0.8,
  },
  cardIcon: {
    fontSize: 20,
  },
  cardNumber: {
    fontSize: 42,
    fontWeight: "800",
    color: "#fff",
    marginTop: 8,
  },
  cardBadge: {
    backgroundColor: "rgba(255,255,255,0.25)",
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    alignSelf: "flex-start",
  },
  cardBadgeText: {
    fontSize: 11,
    color: "#fff",
    fontWeight: "600",
  },
  cardSubLabel: {
    fontSize: 12,
    color: "rgba(255,255,255,0.8)",
    marginTop: 4,
  },
  cycleRow: {
    flexDirection: "row",
    gap: 14,
    marginBottom: 24,
  },
  cycleCard: {
    flex: 1,
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  cycleCardGreen: {
    backgroundColor: "#E1F5EE",
  },
  cycleCardAmber: {
    backgroundColor: "#FAEEDA",
  },
  cycleIcon: {
    fontSize: 24,
  },
  cycleNumber: {
    fontSize: 22,
    fontWeight: "800",
    color: "#1a1a1a",
  },
  cycleLabel: {
    fontSize: 11,
    color: "#888",
    fontWeight: "500",
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 12,
  },
  quickCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
    marginBottom: 10,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 2,
  },
  quickIcon: {
    width: 48,
    height: 48,
    borderRadius: 14,
    justifyContent: "center",
    alignItems: "center",
  },
  quickIconText: {
    fontSize: 22,
  },
  quickInfo: {
    flex: 1,
  },
  quickTitle: {
    fontSize: 15,
    fontWeight: "600",
    color: "#1a1a1a",
  },
  quickSub: {
    fontSize: 12,
    color: "#aaa",
    marginTop: 2,
  },
  quickArrow: {
    fontSize: 22,
    color: "#ccc",
    fontWeight: "300",
  },
  fabOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0,0,0,0.3)",
  },
  fabActions: {
    position: "absolute",
    bottom: 90,
    right: 20,
    gap: 10,
  },
  fabActionItem: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    justifyContent: "flex-end",
  },
  fabActionLabel: {
    backgroundColor: "#fff",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 20,
    fontSize: 14,
    fontWeight: "600",
    color: "#1a1a1a",
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  fabActionIcon: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#000",
    shadowOpacity: 0.2,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 4,
  },
  fabActionIconText: {
    fontSize: 20,
  },
  fab: {
    position: "absolute",
    bottom: 24,
    right: 20,
    width: 58,
    height: 58,
    borderRadius: 29,
    backgroundColor: "#FF4B8B",
    justifyContent: "center",
    alignItems: "center",
    shadowColor: "#FF4B8B",
    shadowOpacity: 0.4,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
  },
  fabOpen: {
    backgroundColor: "#444",
  },
  fabIcon: {
    fontSize: 28,
    color: "#fff",
    fontWeight: "300",
    lineHeight: 32,
  },
});

export default styles;
