import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F5F6FA" },
  content: { padding: 16, paddingBottom: 40 },
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  consentCard: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
  },
  consentHeader: { flexDirection: "row", alignItems: "center", gap: 12 },
  consentIcon: { fontSize: 28 },
  consentTitle: { fontSize: 15, fontWeight: "700", color: "#1a1a1a" },
  consentDate: { fontSize: 12, color: "#888", marginTop: 2 },
  badge: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
  },
  badgeGreen: { backgroundColor: "#E1F5EE" },
  badgeRed: { backgroundColor: "#FCEBEB" },
  badgeText: { fontSize: 12, fontWeight: "700", color: "#0F6E56" },
  versionRow: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 0.5,
    borderTopColor: "#eee",
  },
  versionText: { fontSize: 11, color: "#aaa" },
  versionDot: { fontSize: 11, color: "#ccc" },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "700",
    color: "#1a1a1a",
    marginBottom: 12,
    marginTop: 8,
  },
  rightItem: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 14,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  rightIcon: { fontSize: 20 },
  rightTitle: { fontSize: 14, fontWeight: "600", color: "#1a1a1a" },
  rightDesc: { fontSize: 12, color: "#888", marginTop: 2 },
  dpoCard: {
    backgroundColor: "#EEF0FE",
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
    borderLeftWidth: 4,
    borderLeftColor: "#9B6FE8",
  },
  dpoTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: "#3C3489",
    marginBottom: 6,
  },
  dpoText: { fontSize: 12, color: "#555", lineHeight: 18 },
  dpoEmail: { fontSize: 14, fontWeight: "700", color: "#9B6FE8", marginTop: 6 },
  dpoNote: { fontSize: 11, color: "#888", marginTop: 4 },
  docBtn: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOpacity: 0.04,
    shadowRadius: 4,
    elevation: 1,
  },
  docIcon: { fontSize: 24 },
  docTitle: { fontSize: 14, fontWeight: "600", color: "#1a1a1a" },
  docSub: { fontSize: 12, color: "#aaa", marginTop: 2 },
  docArrow: { fontSize: 20, color: "#ccc" },
  exportBtn: {
    backgroundColor: "#EEF0FE",
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
  },
  exportBtnText: { color: "#3C3489", fontSize: 14, fontWeight: "600" },
  revokeBtn: {
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: "center",
    borderWidth: 1.5,
    borderColor: "#E24B4A",
    marginBottom: 20,
  },
  revokeBtnText: { color: "#E24B4A", fontSize: 14, fontWeight: "600" },
  footer: { fontSize: 11, color: "#aaa", textAlign: "center", lineHeight: 18 },
});

export default styles;
