import { StyleSheet } from "react-native";
import { colors } from "../theme/color";

const styles = StyleSheet.create({
  container: { flex: 1 },
  map: { flex: 1, minHeight: 200 },
  panel: {
    backgroundColor: colors.background,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "65%",
    flexShrink: 1, // <--- 1. ADICIONE ESTA LINHA AQUI
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowRadius: 10,
    shadowOffset: { width: 0, height: -4 },
    elevation: 8,
  },
  panelScroll: {
    flexGrow: 1,
  },
  panelScrollContent: {
    paddingBottom: 24,
  },
  filterBar: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  filterToggleBtn: {
    paddingVertical: 4,
  },
  filterToggleText: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1D9E75",
  },
  filterBadge: {
    fontSize: 11,
    color: "#E24B4A",
    fontWeight: "600",
  },
  filterSection: {
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  filterLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#aaa",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginBottom: 8,
  },
  chip: {
    paddingHorizontal: 14,
    paddingVertical: 7,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ddd",
    marginRight: 8,
    backgroundColor: "#fff",
  },
  chipActive: {
    backgroundColor: "#1D9E75",
    borderColor: "#1D9E75",
  },
  chipText: {
    fontSize: 12,
    color: "#555",
    fontWeight: "500",
  },
  chipTextActive: {
    color: "#fff",
    fontWeight: "700",
  },
  excludeItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 9,
    paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#eee",
    marginBottom: 6,
    backgroundColor: "#fff",
  },
  excludeItemActive: {
    borderColor: "#E24B4A",
    backgroundColor: "#FCEBEB",
  },
  excludeName: {
    fontSize: 13,
    fontWeight: "600",
    color: "#1a1a1a",
  },
  excludeNameActive: {
    color: "#A32D2D",
    textDecorationLine: "line-through",
  },
  excludeSpec: {
    fontSize: 11,
    color: "#888",
  },
  excludeIcon: {
    fontSize: 18,
    color: "#ccc",
    fontWeight: "700",
  },
  excludeIconActive: {
    color: "#E24B4A",
  },
  startSection: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  sectionLabel: {
    fontSize: 11,
    fontWeight: "700",
    color: "#aaa",
    textTransform: "uppercase",
    letterSpacing: 0.5,
    marginBottom: 8,
  },
  startRow: {
    flexDirection: "row",
    gap: 8,
    alignItems: "center",
  },
  startInput: {
    flex: 1,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    fontSize: 13,
    color: "#1a1a1a",
  },
  gpsBtn: {
    backgroundColor: colors.ColorBtn,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    minWidth: 44,
    alignItems: "center",
  },
  gpsBtnText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  searchBtn: {
    backgroundColor: colors.text,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 9,
    minWidth: 44,
    alignItems: "center",
  },
  searchBtnText: { color: "#fff", fontWeight: "700", fontSize: 12 },
  distanceCards: {
    flexDirection: "row",
    gap: 8,
    marginTop: 10,
  },
  distCard: {
    flex: 1,
    borderRadius: 8,
    padding: 10,
  },
  distCardNearest: { backgroundColor: colors.backgroundsecond },
  distCardFarthest: { backgroundColor: "#FAECE7" },
  distCardLabel: {
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    color: "#888",
    marginBottom: 2,
  },
  distCardName: { fontSize: 12, fontWeight: "600", color: "#1a1a1a" },
  distCardKm: { fontSize: 13, fontWeight: "700", color: "#555", marginTop: 2 },
  generateBtn: {
    margin: 14,
    backgroundColor: colors.text,
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: "center",
  },
  generateBtnText: { color: "#fff", fontWeight: "700", fontSize: 15 },
  panelHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: "#eee",
  },
  panelTitle: { fontSize: 15, fontWeight: "700", color: "#1a1a1a" },
  panelSub: { fontSize: 11, color: "#888", marginTop: 1 },
  regenBtn: {
    backgroundColor: colors.backgroundsecond,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  regenText: { color: colors.text, fontWeight: "600", fontSize: 12 },
  stopsList: { paddingHorizontal: 14 },
  stopItem: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    borderBottomWidth: 0.5,
    borderBottomColor: "#f0f0f0",
    gap: 12,
  },
  stopNumber: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.text,
    justifyContent: "center",
    alignItems: "center",
    flexShrink: 0,
  },
  stopNearest: { backgroundColor: "#0F6E56" },
  stopFarthest: { backgroundColor: "#D85A30" },
  stopNumberText: { color: "#fff", fontWeight: "700", fontSize: 13 },
  stopInfo: { flex: 1 },
  stopName: { fontSize: 14, fontWeight: "600", color: "#1a1a1a" },
  stopSpecialty: { fontSize: 12, color: colors.text, marginTop: 1 },
  stopDist: { fontSize: 11, color: "#aaa", marginTop: 2 },
  stopComment: {
    fontSize: 11,
    color: "#aaa",
    fontStyle: "italic",
    marginTop: 2,
  },
  navIcon: { fontSize: 18, color: "#ccc" },
  checkInBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1.5,
    borderColor: "#ddd",
    justifyContent: "center",
    alignItems: "center",
    marginLeft: 8,
  },
  checkInVisited: {
    backgroundColor: "#E1F5EE",
    borderColor: "#1D9E75",
  },
  checkInNotVisited: {
    backgroundColor: "#FCEBEB",
    borderColor: "#E24B4A",
  },
  checkInBtnText: {
    fontSize: 14,
    fontWeight: "700",
    color: "#888",
  },
  todayBtn: {
    alignSelf: "flex-start",
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 20,
    backgroundColor: "#E1F5EE",
    borderWidth: 1,
    borderColor: "#1D9E75",
    marginBottom: 10,
  },
  todayBtnText: {
    fontSize: 12,
    fontWeight: "600",
    color: "#0F6E56",
  },
});

export default styles;
